### PR TITLE
Fixed #1180

### LINKED ISSUE #1180: CSS variables containing only whitespace are incorrectly removed
### Environment

Just testing at https://clean-css.github.io/

### Input CSS

```css
.inset {
  --inset: inset;
}

.outset {
  --inset: ;
}

.shadow {
  box-shadow: var(--inset) 0 2px 2px #0004;
}
```

### Actual output CSS

```css
.inset{--inset:inset}.shadow{box-shadow:var(--inset) 0 2px 2px #0004}
```

### Expected output CSS

```css
.inset{--inset:inset}.outset{--inset: ;}.shadow{box-shadow:var(--inset) 0 2px 2px #0004}
```

### Explanation

Whitespace is a valid value for a CSS variable, like this:

```css
--my-var: ;
```

This is semantically _not_ the same as:

```css
--my-var:;
```

From [CSS Custom Properties for Cascading Variables Module Level 1](https://www.w3.org/TR/css-variables-1/#syntax):

> Note: While <declaration-value> must represent at least one token, that one token may be whitespace. This implies that --foo: ; is valid, and the corresponding var(--foo) call would have a single space as its substitution value, but --foo:; is invalid.

Because of this issue, clean-css currently cannot be used with Tailwind CSS, as we rely on this feature a lot to support class composition in the framework.

Thanks for your awesome work on this lib ❤️

### PR DESCRIPTION
**Pull request by SuyashJoshi179**
CSS variables containing only whitespace will persist from now on.

### CODE REVIEW

**Comment by yellow1912** [comment]
Nice, I run into this issue when cleaning css generated from tailwind.

**Comment by jakubpawlowicz** [comment]
Hey @SuyashJoshi179 thanks for the fix. Can you please add at least three tests to cover this feature?

1) tokenizer - https://github.com/clean-css/clean-css/blob/master/test/tokenizer/tokenize-test.js
2) Level 1 optimizations - https://github.com/clean-css/clean-css/blob/master/test/optimizer/level-1/optimize-test.js
3) Level 2 optimizations - https://github.com/clean-css/clean-css/blob/master/test/optimizer/level-2/optimize-test.js

I just want to make sure that tokenizer change is covered by test - 1 - and optimizers don't remove that empty variable anywhere down the road - 2 & 3.

**Comment by SuyashJoshi179** [comment]
Yes, I'll add those.

File: lib/tokenizer/tokenize.js [hunk 1]
```diff
@@ -367,6 +371,8 @@ function intoTokens(source, externalContext, internalContext, isNested) {
       isBufferEmpty = true;
     } else if (character == Marker.SEMICOLON && level == Level.RULE && propertyToken && isBufferEmpty) {
       // semicolon after bracketed value at rule level, e.g. a{color:rgb(...);<--
+      if(isVariable && !propertyToken[2]) propertyToken.push([Token.PROPERTY_VALUE, ' ', [originalMetadata(metadata, ' ', externalContext)]]);
```
Comment (jakubpawlowicz) [inline lib/tokenizer/tokenize.js:374]: 2 changes here: 

1) Please move this `if` case up one level instead of nesting it within existing clause, e.g.

```js
} else if (character == Marker.SEMICOLON && level == Level.RULE && propertyToken && isBufferEmpty && isVariable && !propertyToken[2]) {
  // semicolon after empty variable at rule level, e.g. a{--variable: ;<--
  propertyToken.push([Token.PROPERTY_VALUE, ' ', [originalMetadata(metadata, ' ', externalContext)]]);
  isVariable = false;
  propertyToken = null;
  seekingValue = false;
} else if (character == Marker.SEMICOLON && level == Level.RULE && propertyToken && isBufferEmpty) {
  ...
```

2) Please add a space between `if` and `(` so it's `if (`

File: lib/tokenizer/tokenize.js [hunk 2]
```diff
@@ -454,6 +460,8 @@ function intoTokens(source, externalContext, internalContext, isNested) {
       isBufferEmpty = true;
     } else if (character == Marker.CLOSE_CURLY_BRACKET && level == Level.RULE) {
       // close brace after a rule, e.g. a{color:red;}<--
+      if(isVariable && propertyToken && !propertyToken[2]) propertyToken.push([Token.PROPERTY_VALUE, ' ', [originalMetadata(metadata, ' ', externalContext)]]);
```
Comment (jakubpawlowicz) [inline lib/tokenizer/tokenize.js:463]: Similar as above!

**Review by jakubpawlowicz — CHANGES_REQUESTED** [review]
Two small changes and we are good to go.

File: lib/tokenizer/tokenize.js (hunk 1 above)
Comment (SuyashJoshi179) [reply lib/tokenizer/tokenize.js]: Done..

File: lib/tokenizer/tokenize.js (hunk 2 above)
Comment (SuyashJoshi179) [reply lib/tokenizer/tokenize.js]: Done..

**Comment by yellow1912** [comment]
@jakubpawlowicz can you check and consider merging when you have time?

**Comment by jakubpawlowicz** [comment]
Hey @SuyashJoshi179 - please see my change - d114677edb244917f50941a9f19bceeb55408cfc and sorry if I didn't made myself clear enough regarding what I wanted. If you could cherry pick it into your branch, push it to this PR, then we can merge the PR asap.

Thanks!

**Comment by SuyashJoshi179** [comment]
@jakubpawlowicz   I have refactored the code as per your requirement.

**Review by jakubpawlowicz — APPROVED** [review]

**Comment by jakubpawlowicz** [comment]
Cool, it's done now. I will release it today, perhaps as clean-css 5.2.0.

**Comment by jakubpawlowicz** [comment]
It's released in clean-css 5.2.0. Thanks a lot @SuyashJoshi179!
